### GET qcms
GET http://localhost:3001/qcms


### GET cat by id
GET http://localhost:3001/qcms/1

###Creer un qcm
POST http://localhost:3001/qcms
Content-Type: application/json

{
  "data": {
    "name": "Culture Numérique"
  }
}


###Récupère le résultat d'un QCM (score) |
POST http://localhost:3001/qcms
Content-Type: application/json

{
  "data": {
    "name": "Les Fleurs",
    "questions": [
      {
        "description": "Quelle fleur est souvent associée à l'amour ?",
        "propositions": [
          { "description": "La rose", "isValid": true },
          { "description": "Le tournesol", "isValid": false },
          { "description": "La marguerite", "isValid": false }
        ]
      },
      {
        "description": "Quelles fleurs peuvent être jaunes ?",
        "propositions": [
          { "description": "Le tournesol", "isValid": true },
          { "description": "La jonquille", "isValid": true },
          { "description": "Le cactus", "isValid": false }
        ]
      },
      {
        "description": "De quoi une fleur a-t-elle besoin pour pousser ?",
        "propositions": [
          { "description": "De lumière", "isValid": true },
          { "description": "D'eau", "isValid": true },
          { "description": "De plastique", "isValid": false }
        ]
      }
    ]
  }
}

###Creer un qcm
POST http://localhost:3001/questions
Content-Type: application/json
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJzYWJyaW5hLWxvZ2luQHRlc3QuZnIiLCJpYXQiOjE3ODAzOTM0ODAsImV4cCI6MTc4MDQwMDY4MH0.h1no01eg7Fibg6b0OtLVMOd_zGVHmu_1lELgUUvc4DY"

{
  "data": {
    "description": "Que signifie HTTP ?",
    "qcmId": 1
  }
}

###Soumettre une reponse
GET  http://localhost:3001/qcms/1/result
Content-Type: application/json

{
  "data": {
    "propositionId": 1,
    "isChecked": true
  }
}




###Soumettre une reponse
POST http://localhost:3001/qcms/1/response
Content-Type: application/json
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJzYWJyaW5hLWxvZ2luQHRlc3QuZnIiLCJpYXQiOjE3ODAzOTQzMDYsImV4cCI6MTc4MDQwMTUwNn0.zBSwbe7QSSDFNR5ks2ujd0SN-PdDdZ_N1ScuBK12Dww"

{
  "data": {
    "propositionId": 1,
    "isChecked": true
  }
}

### Soumettre une réponse
POST http://localhost:3001/qcms/1/response
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJzYWJyaW5hLWxvZ2luQHRlc3QuZnIiLCJpYXQiOjE3ODAzOTQzMDYsImV4cCI6MTc4MDQwMTUwNn0.zBSwbe7QSSDFNR5ks2ujd0SN-PdDdZ_N1ScuBK12Dww

{
  "data": {
    "propositionId": 1,
    "isChecked": true
  }
}


### GET cat by id
GET http://localhost:3001/qcms/1/question